name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g webfont-assistant
        webfont-assistant --config "assets/fonts/ArandaIcons.was"
      env:
        CI: true
    - uses: actions/download-artifact@v1.0.0
    - name: Download artifact
      with:
        # Artifact name
        name: "Icons"
        # Directory containing files to upload
        path: "dist/"
